# Generated by Django 3.0.7 on 2020-06-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200629_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='')),
                ('company', models.TextField(default='')),
                ('duration', models.TextField(default='')),
                ('item1', models.TextField(default='')),
                ('item2', models.TextField(default='')),
                ('item3', models.TextField(default='')),
                ('item4', models.TextField(default='')),
            ],
        ),
    ]
