# Generated by Django 3.0.7 on 2020-06-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_cvexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvexperience',
            name='item3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cvexperience',
            name='item4',
            field=models.TextField(blank=True, default=''),
        ),
    ]
