# Generated by Django 3.0.7 on 2020-06-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200630_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvexperience',
            name='item4',
        ),
        migrations.AlterField(
            model_name='cvexperience',
            name='item3',
            field=models.TextField(default=''),
        ),
    ]
