# Generated by Django 3.0.7 on 2020-06-30 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200630_0149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HardSkills',
            new_name='HardSkill',
        ),
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='SoftSkills',
            new_name='SoftSkill',
        ),
    ]
