# Generated by Django 3.0.7 on 2020-06-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='role',
            new_name='degree',
        ),
    ]
