# Generated by Django 3.0.7 on 2020-06-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200630_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='item1_grade',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='education',
            name='item2_grade',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='education',
            name='item3_grade',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
    ]
